name: Test

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Install Python 3.10 with uv
      run: |
        uv python install 3.10
    
    - name: Install nvm and Node.js 24
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 24
        nvm use 24
        echo "$NVM_DIR/versions/node/$(nvm version)/bin" >> $GITHUB_PATH
    
    - name: Create virtual environment and install Python dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv sync
    
    - name: Install frontend dependencies
      run: |
        cd  src/lerobot_data_studio/frontend
        npm install
    
    - name: Run backend tests
      run: |
        source .venv/bin/activate
        uv run pytest
    
    - name: Run frontend tests
      run: |
        cd src/lerobot_data_studio/frontend
        npm run test