name: Test

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
   
    - name: Install nvm and Node.js 24
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 24
        nvm use 24
        echo "$NVM_DIR/versions/node/$(nvm version)/bin" >> $GITHUB_PATH
    
    - name: Install frontend dependencies
      run: |
        cd  src/lerobot_data_studio/frontend
        npm install
    
    - name: Run frontend tests
      run: |
        cd src/lerobot_data_studio/frontend
        npm run test